services:
  - type: web
    name: poker-web-game
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
