services:
  - type: web
    name: poker-web-game
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client --include=dev && npm run build --prefix client
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22.16.0"
